#!/bin/bash

for FILE in /ebc_data/awwohns/selection/getting_1000g_refs/gbr_vcfs/gbr_chrs/*.vcf; do
        echo ${FILE}
	shortName=$(basename $FILE)
	chrName=${shortName:0:4}
	echo ${chrName}
	awk 'NR > 4 { print }' ${FILE} > ${shortName} 
	
done



for rsid in . && freq in /ebc_data/awwohns/selection/getting_1000g_refs/allele_freqs/allelefreqs; do
	join --header -j 2 -o 1.1,1.2,1.3,1.4,1.5,1.6,2.3 rsid freq > ${rsid}joined.frq
done

